// prc_rest,x2_mod_def_rest
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerrest event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_rest", OBJECT_SELF);
    ExecuteScript("x2_mod_def_rest", OBJECT_SELF);
}
