// prc_onmodload,x2_mod_def_load
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onmoduleload event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onmodload", OBJECT_SELF);
    FloatingTextStringOnCreature("hif_onmoduleload running", GetFirstPC());
    ExecuteScript("x2_mod_def_load", OBJECT_SELF);
}
