// prc_equip,x2_mod_def_equ
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerequipitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_equip", OBJECT_SELF);
    ExecuteScript("x2_mod_def_equ", OBJECT_SELF);
}
