// prc_unequip,x2_mod_def_unequ
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerunequipitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_unequip", OBJECT_SELF);
    ExecuteScript("x2_mod_def_unequ", OBJECT_SELF);
}
