// prc_onactivate,x2_mod_def_act
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onactivateitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onactivate", OBJECT_SELF);
    ExecuteScript("x2_mod_def_act", OBJECT_SELF);
}
