// prc_onaquire,x2_mod_def_aqu
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onacquireitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onaquire", OBJECT_SELF);
    ExecuteScript("x2_mod_def_aqu", OBJECT_SELF);
}
