// prc_onrespawn,nw_o0_respawn
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerrespawn event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onrespawn", OBJECT_SELF);
    ExecuteScript("nw_o0_respawn", OBJECT_SELF);
}
