// prc_ondeath,nw_o0_death
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerdeath event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_ondeath", OBJECT_SELF);
    ExecuteScript("nw_o0_death", OBJECT_SELF);
}
